services: docker

before_install:
  - docker -v
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop
install:
  # Start the docker stuff
  - docker-compose up -d
  - sleep 10
script:
  # Code styles
  - docker-compose exec web sh -c "flake8 --exclude=migrations --ignore=E121,E203,E226,E402,E501,F401,F403,W503 ./"
  # Run tests
  - docker-compose exec web pytest
  # Show logs
  - docker-compose logs --tail=20 web
