version: '3.3'

volumes:
    postgres_data: {}

services:
  web: &web
    container_name: web
    build:
      context: .
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app
    command: /app/scripts/dev.sh
    entrypoint: /app/scripts/entrypoint.sh
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    container_name: redis
    image: redis:4.0

  worker:
    <<: *web
    container_name: worker
    ports: []
    command: ["celery", "worker", "--app=config", "--loglevel=info"]

  jupyter:
    container_name: jupyter
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    command: ["python", "manage.py", "shell_plus", "--notebook"]
    network_mode: "host"
    volumes:
      - ./src:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.jupyter