version: '3.3'

volumes:
    postgres_data: {}

services:
  web:
    container_name: web
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - ./src:/app
    command: /app/scripts/start.sh
    entrypoint: /app/scripts/entrypoint.sh
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local


  postgres:
    container_name: postgres
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
