# Generated by Django 2.2.24 on 2024-07-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys24', '0002_auto_20240421_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerstat',
            name='is_senility',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is Senility'),
        ),
        migrations.AddField(
            model_name='farmerstat',
            name='sample_group',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Origin'), (2, 'Mix')], null=True, verbose_name='Sample Group'),
        ),
        migrations.AddField(
            model_name='stratify',
            name='is_senility',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Is Senility'),
        ),
    ]
