# Generated by Django 2.2.24 on 2025-03-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys25', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidy',
            name='hire_channel_extra',
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='hire_channels',
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='lack_response_extra',
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='lack_responses',
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='max_hourly_pay_extra',
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='max_hourly_pays',
        ),
    ]
